# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c6455d5894836076faeb7a0465b77ea7c5086996321440e16b5c8351c81b0d219388c082a534f0dd2d24817ef019e6dfa78538f9ed1eb0729a2d7d86d4bcb82

test:
  secret_key_base: 0d41d0a4a0e946c1cb6b5da3675492f6fb7ba04a5ec46a9d24a7f44db89d7c1f1cfb37d543d7d3bce770a8555464f5d0891b9b073c42260cc060bc741db9a412

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
